from enum import Enum

class Department(Enum):
        
    MICROBIOLOGY = 1
    FOOD_SCIENCE = 2
    BIOCHEMISTRY = 3
    GEOSCIENCES = 4
    BIOLOGICAL_SCIENCES = 5
    PHYSICS = 6
    COMPUTER_SCI = 7
    CHEMICAL_SCIENCES = 8
    PHYSICAL_SCIENCE = 9
    ACCOUNTING = 11
    MASS_COMMUNICATION = 12
    BUSINESS_ADMIN = 13
    MUSIC = 14
    LANGUAGES = 15
    ECONOMICS = 16
    PHILOSOPHY_RELIGION = 17
    IRPM = 18
    MATHEMATICS = 19
    CYBER_SECURITY = 20
    PUBLIC_ADMINISTRATION = 21
    BANKING_FINANCE = 22
    CHEMISTRY = 23
    SOFTWARE_ENGINEERING = 24
    INDUSTRIAL_CHEMISTRY = 25
    FINE_AND_APPLIED_ART = 26
    NURSING_SCIENCE = 27
    UNKOWN_DEPARTMENT = 100


DEPARTMENT_CHOICES = (
    (Department.MICROBIOLOGY.value, "MICROBIOLOGY"),
    (Department.FOOD_SCIENCE.value, "FOOD SCIENCE & TECH"),
    (Department.BIOCHEMISTRY.value, "BIOCHEMISTRY"),
    (Department.GEOSCIENCES.value, "GEOSCIENCES"),
    (Department.BIOLOGICAL_SCIENCES.value, "BIOLOGICAL SCIENCES"),
    (Department.PHYSICS.value, "PHYSICS"),
    (Department.COMPUTER_SCI.value, "COMPUTER SCIENCE"),
    (Department.CHEMICAL_SCIENCES.value,"CHEMICAL SCIENCES"),
    (Department.PHYSICAL_SCIENCE.value, "PHYSICAL SCIENCE"),
    (Department.ACCOUNTING.value, "ACCOUNTING"),
    (Department.MASS_COMMUNICATION.value, "MASS COMMUNICATION"),
    (Department.BUSINESS_ADMIN.value, "BUSINESS ADMIN"),
    (Department.MUSIC.value, "MUSIC"),
    (Department.LANGUAGES.value, "LANGUAGES"),
    (Department.ECONOMICS.value, "ECONOMICS"),
    (Department.PHILOSOPHY_RELIGION.value, "PHILOSOPHY & RELIGION"),
    (Department.IRPM.value, "IND. REL. & PERSONNEL MGT"),
    (Department.CYBER_SECURITY.value, "CYBER SECURITY"),
    (Department.PUBLIC_ADMINISTRATION.value, "PUBLIC ADMINISTRATION"),
    (Department.BANKING_FINANCE.value, "BANKING & FINANCE"),
    (Department.MATHEMATICS.value, "MATHEMATICS"),
    (Department.CHEMISTRY.value, "CHEMISTRY"),
    (Department.SOFTWARE_ENGINEERING.value, "SOFTWARE ENGINEERING"),
    (Department.INDUSTRIAL_CHEMISTRY.value, "INDUSTRIAL CHEMISTRY"),
    (Department.FINE_AND_APPLIED_ART.value, "FINE & APPLIED ART"),
    (Department.NURSING_SCIENCE.value, "NURSING SCIENCE"),
    (Department.UNKOWN_DEPARTMENT.value, "UNKOWN DEPARTMENT"),


)







['MAA', 'PEL']