
MICROBIOLOGY = 1
FOOD_SCIENCE = 2
BIOCHEMISTRY = 3
GEOSCIENCES = 4
BIOLOGICAL_SCIENCES = 5
PHYSICS = 6
COMPUTER_SCI_MATH = 7
CHEMICAL_SCIENCES = 8
PHYSICAL_SCIENCE = 9
GEOPHYSICS = 10
ACCOUNTING = 11
MASS_COMMUNICATION = 15
BUSINESS_ADMIN = 16
MUSIC = 17
LANGUAGES = 18
ECONOMICS = 19
PHILOSOPHY_RELIGION = 20
IRPM = 21

DEPARTMENT_CHOICES = (
    (MICROBIOLOGY, "MICROBIOLOGY"),
    (FOOD_SCIENCE, "FOOD SCIENCE & TECH"),
    (BIOCHEMISTRY, "BIOCHEMISTRY"),
    (GEOSCIENCES, "GEOSCIENCES"),
    (BIOLOGICAL_SCIENCES, "BIOLOGICAL SCIENCES"),
    (PHYSICS, "PHYSICS"),
    (COMPUTER_SCI_MATH, "COMPUTER SCI & MATHS"),
    (CHEMICAL_SCIENCES,"CHEMICAL SCIENCES"),
    (PHYSICAL_SCIENCE, "PHYSICAL SCIENCE"),
    (GEOPHYSICS, "GEOPHYSICS"),
    (ACCOUNTING, "ACCOUNTING"),
    (MASS_COMMUNICATION, "MASS COMMUNICATION"),
    (BUSINESS_ADMIN, "BUSINESS ADMIN"),
    (MUSIC, "MUSIC"),
    (LANGUAGES, "LANGUAGES"),
    (ECONOMICS, "ECONOMICS"),
    (PHILOSOPHY_RELIGION, "PHILOSOPHY & RELIGION"),
    (IRPM, "IND. REL. & PERSONNEL MGT"),
)
